<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

	<ItemGroup>
	  <Folder Include="Users\" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\TaskFlow.Commom\TaskFlow.Common.csproj" />
	  <ProjectReference Include="..\TaskFlow.Domain\TaskFlow.Domain.csproj" />
	</ItemGroup>
</Project>
