<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Repositories\**" />
    <Compile Remove="Service\**" />
    <EmbeddedResource Remove="Repositories\**" />
    <EmbeddedResource Remove="Service\**" />
    <None Remove="Repositories\**" />
    <None Remove="Service\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TaskFlow.Commom\TaskFlow.Common.csproj" />
  </ItemGroup>

</Project>
